version: '3'
services:
  mock-sso:
    image: ukti/mock-sso
    environment:
      MOCK_SSO_TOKEN: token
      MOCK_SSO_VALIDATE_TOKEN: 'true'
      MOCK_SSO_USERNAME: vyvyan.holland@email.com
      MOCK_SSO_EMAIL_USER_ID: vyvyan.holland-20a0353f@id.mock-sso
      MOCK_SSO_SCOPE: test
    ports:
      - "8080:8080"
